# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Orikaban Theme"
license = ""
licenselink = ""
description = ""
homepage = ""
tags = ["website", "responsive", "blog", "Multilingual"]
features = []
min_version = "0.79.0"

[author]
  name = "Ben Sekulowicz"
  homepage = "https://beseku.com"
