analytics:
  - "<script async defer data-domain=\"llama.studio\" src=\"https://plausible.io/js/plausible.js\"></script>"
  - "<script async defer src=\"https://scripts.simpleanalyticscdn.com/latest.js\"></script>"
  - "<script defer src=\"https://static.cloudflareinsights.com/beacon.min.js\" data-cf-beacon=\"{'token': 'c1b88c60be644e469a2af8f7a978033c'}\"></script>"

styleSheets: 
  - "stylesheets/custom.scss"